name: publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-20.04
    environment:
        name: pypi
        url: https://pypi.org/project/webtoon-api/
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-dev --no-root
      - name: Build package
        run: |
          poetry build --no-interaction
      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
