name: publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}
          poetry build --no-interaction
          poetry publish --no-interaction
